<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PetLoveCommunity.Domain\PetLoveCommunity.Domain.csproj" />
    <ProjectReference Include="..\PetLoveCommunity.Application\PetLoveCommunity.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
